// /*Data flow summary
//   Data: 'BEDASSIGNMENTS' is an array of objects which consist of 'bed' and 'notes' properties.
//   <BedAssignments /> takes 'BEDASSIGNMENTS' and passes it down to AssignmentTable.
//   <AssignmentTable />  runs a forEach loop through the array and passes each object with 'BEDASSIGNMENTS' down to <BedRow /> and pushes each <BedRow /> to a 'rows' array.
//   <BedRow /> takes each object that was sent down from <AssignmentTable /> and returns an HTML table row with bed number and notes embedded (that are not null).
//   After <AssignmentTable /> pushes all the <BedRow /> elements into the 'rows' array it returns a table with the 'rows' array.
//   <BedAssignments /> renders <AssignmentTable /> table and ReactDOM.render attaches it to div with ID 'content'.
// */

//SANDBOX

var BedRow = React.createClass({
  render: function() {
    var bed = this.props.assignment.id
    return (
      <tr>
        <td>{bed}</td>
        <td>{this.props.assignment.notes}</td>
      </tr>
    );
  }
});

var AssignmentTable = React.createClass({
  render: function() {
    var rows = [];
    this.props.assignments.forEach(function(assignment) {
      rows.push(<BedRow assignment={assignment} key={assignment.id} />);
    }.bind(this));
    return (
      <table>
        <thead>
          <tr>
            <th>Bed</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>
    );
  }
});

var BedAssignments = React.createClass({
  
  loadCommentsFromServer: function() {
    $.ajax({
      url: this.props.url,
      dataType: 'json',
      cache: false,
      success: function(data) {
        console.log('BedAssignmentData', data);
        this.setState({data: data});
      }.bind(this),
      error: function(xhr, status, err) {
        console.error(this.props.url, status, err.toString());
      }.bind(this)
    });
  },

  handleCommentSubmit: function(comment) {
    var comments = this.state.data;
    // Optimistically set an id on the new comment. It will be replaced by an
    // id generated by the server. In a production application you would likely
    // not use Date.now() for this and would have a more robust system in place.
    
    comment.id = Date.now();
    var newComments = comments.concat([comment]);
    this.setState({data: newComments});
    $.ajax({
      url: this.props.url,
      dataType: 'json',
      type: 'POST',
      data: comment,
      success: function(data) {
        this.setState({data: data});
      }.bind(this),
      error: function(xhr, status, err) {
        this.setState({data: comments});
        console.error(this.props.url, status, err.toString());
      }.bind(this)
    });
  },

  getInitialState: function() {
    return {data: []};
  },

  componentDidMount: function() {

    // this.loadCommentsFromServer();
    // setInterval(this.loadCommentsFromServer, this.props.pollInterval);

  },

  componentWillUpdate: function() {
    //placeholder function. Not using it currently.
  },

  componentDidUpdate: function() {
    //placeholder function. Not using it currently.
  },

  render: function() {
    return (
      <div>
        <CommentForm onCommentSubmit={this.handleCommentSubmit} />
        <AssignmentTable
          assignments = {this.state.data}
        />
      </div>
    );
  }
});


var CommentForm = React.createClass({
  getInitialState: function() {
    return {first: '', last: ''};
  },
  handleFirstChange: function(e) {
    this.setState({first: e.target.value});
  },
  handleLastChange: function(e) {
    this.setState({last: e.target.value});
  },
  handleSubmit: function(e) {
    e.preventDefault();
    var first = this.state.first.trim();
    var last = this.state.last.trim();
    if (!last || !first) {
      return;
    }
    this.props.onCommentSubmit({first: first, last: last});
    //Commenting out setState so that the submitted user stays in state
    //this.setState({first: '', last: ''});
  },
  render: function() {
    return (
      <form className="commentForm" onSubmit={this.handleSubmit}>
        <input
          type="text"
          placeholder="First name"
          value={this.state.first}
          onChange={this.handleFirstChange}
        />
        <input
          type="text"
          placeholder="Last name"
          value={this.state.last}
          onChange={this.handleLastChange}
        />
        <input type="submit" value="Post" />
      </form>
    );
  }
});



ReactDOM.render(
  <BedAssignments url="/api/comments" pollInterval={2000} />,
  document.getElementById('content')
);
